//
// ID for the visualisation
//
// Page ID
//
P_ID_GEN_1          = 1

P_ID_ADMIN_HEATING  = 2
      

// weboutput() , SpWebOutHkGen()
ID_WebOutHK1	 = 2
ID_WebOutHK3	 = 3
ID_WebOutHK4	 = 4



// Button global
ID_B_BOOST_EG_K             = 10
ID_B_OG1_MARISA_MEG_FROST   = 11
ID_B_OG1_BUERO_MEG_FROST    = 12
ID_B_OG1_EMILIA_MEG_FROST   = 13
ID_S_EG_WC_HZ               = 14
ID_S_EG_ESSZ_RAD            = 15
ID_S_EG_WOHNZ_RAD           = 16
ID_B_EG_GARDROBE_RAD        = 17
ID_B_EG_ESSZ_FBH            = 18
ID_B_EG_WOHNZ_FBH           = 19
ID_S_EG_EMO_TREPPE          = 20
ID_B_BOOST_EG_Kueche        = 21
ID_S_HK1_MODE               = 22
ID_S_HK4_MODE               = 23
ID_S_HK4_DACH_EAST          = 24
ID_B_UVR_ON                 = 25
ID_B_DACH_BAD_FBH           = 26
ID_B_DACH_WEST_FBH          = 27
ID_B_DACH_WEST_RAD          = 28
ID_S_OG1_BAD_RAD            = 29
ID_S_OG1_EMO_GAST           = 30
ID_B_BOOST_OG1_BAD          = 31
ID_S_BOOST_OG1_BAD          = 32
