// $Id: RemMem.inc 68 2014-10-07 13:38:32Z asc $
REMDELAY = 1000u64
// condtants for UVR1611 and MDT HzActor
//
testV = 10u08
/////////////////////
// constants
EMPTYSTRING = $$  /* for BMXRemanent8.lib */
//CRLF        = $$
/////////////////////////
// Position for Remanant Speicher
// Heizung
// EG

RemSlotfNightOverride_EG      = 1u16
RemfNightOverride_EG_Rem      = AUS
RemfNightOverride_EG_W        = AUS


RemSlotfNightOverride_Dach    = 2u16
RemfNightOverride_Dach_Rem    = AUS
RemfNightOverride_Dach_W      = AUS


RemSlotHK4Mode                = 3u16
RemHK4Mode_Rem                = PCUVR_PCAUTO
RemHK4Mode_W                  = AUS